<paper-component simple="true" class="page">
  <div class="header">
    <h1>Testing Page</h1>
    <p>Choose subject for testing</p>
  </div>

  <div class="semestr-list">
    @for (semestr in semestrs) {
    <paper-component simple="true" class="semestr-item">
      <p>Semestr @(semestr.number)</p>
      <div class="subject-list">
        @for (subject in semestr.subjects) {
        <re-button variant="outlined" color="additional" data-link
          href="/testing/sub?subject=@(encodeURIComponent(JSON.stringify(subject)))">
          <div class="content">
            <div class="meta">
              <div>
                <h3>@(subject.translatedName)</h3>
                <!--<h4>@(subject.name)</h4> -->
              </div>
              <p>Преподаватель: @(subject.teacher)</p>
            </div>
            <div class="chip-column">
              @for (group in subject.groups) {
              <re-chip color="additional">@(group)</re-chip>
              }
            </div>
          </div>
        </re-button>
        }
      </div>
    </paper-component>
    }
  </div>
</paper-component>